version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "12000:5000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - FLASK_ENV=production
      - PORT=5000
  